definitions:
# Schema for Service
  Service:
    type: "object"
    properties:
      name:
        type: "string"
        example: 'ServiceTestName'
      version:
        type: "integer"
        format: "int64"
        example: 1
    xml:
      name: "Service"

