version: "2"
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
#    environment:
#      - VIRTUAL_HOST=test.dmz.teco.edu/api
#      - VIRTUAL_PORT=3000
#      - LETSENCRYPT_HOST=api.test.dmz.teco.edu
  authentication:
      container_name: authentication
      restart: always
      build: ../authentication
      ports:
        - "3002:3002"
      links:
        - mongo
#      environment:
#        - VIRTUAL_HOST=test.dmz.teco.edu/auth
#        - VIRTUAL_PORT=3002
#        - LETSENCRYPT_HOST=auth.test.dmz.teco.edu
  nginx:
      image: nginx
      links:
       - authentication
       - backend
      ports:
        - "80:80"
        - "443:443"
      volumes:
#        - /etc/nginx/certs
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
#        - /usr/share/nginx/html
#        - /var/run/docker.sock:/tmp/docker.sock:ro
#      environment:
#       - DEFAULT_HOST=foo.bar.com
#  nginx-proxy-letsencrypt:
#     image: jrcs/letsencrypt-nginx-proxy-companion
#      volumes_from:
#        - nginx-proxy
#      volumes:
#        - /var/run/docker.sock:/var/run/docker.sock:ro
#      environment:
#        - "DEFAULT_EMAIL=roeddiger@teco.edu"
  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
      environment:
        - NETWORK_ACCESS=internal
