version: "2"
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  website:
    container_name: website
    restart: always
    build: ../meta.website
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - static-content:/usr/src/app/build
  authentication:
    container_name: authentication
    restart: always
    build: ../authentication
    ports:
      - "3002:3002"
    links:
      - mongo
  nginx:
    image: nginx
    restart: always
    links:
     - authentication
     - backend
     - website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-content:/usr/src/app/build
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - NETWORK_ACCESS=internal
volumes:
  static-content:
