version: "2"
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  authentication:
      container_name: authentication
      restart: always
      build: ../authentication
      ports:
        - "3002:3002"
      links:
        - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
