# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        mongodb-version: [4]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Clone auth
      run: git clone https://github.com/teco-kit/explorer-auth
    
    - name: Install Auth
      working-directory: ./explorer-auth
      run:  |
        npm ci
        npm start &
    
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install backend
      run: npm ci
    - name: Test
      run: npm test
  env:
    CI: true
